# note to self: this is only intended for human development use.
# don't touch this or use it for automation.
run:
	pdflatex resume.tex
	pdflatex resume.tex
clean:
	rm -rf resume.{aux,log,out,pdf} 2> /dev/null
